import { toktype, lex, init_lex } from "../src/lex";

const punctuators: toktype[] = [
    toktype.RBRACKET,
    toktype.LBRACKET,
    toktype.RPAREN,
    toktype.LPAREN,
    toktype.RBRACE,
    toktype.LBRACE,
    toktype.DOT,
    toktype.ARROW,
    toktype.PPLUS,
    toktype.MMINUS,
    toktype.BAND,
    toktype.ASTERISK,
    toktype.PLUS,
    toktype.MINUS,
    toktype.TILDE,
    toktype.BANG,
    toktype.SLASH,
    toktype.PERCENT,
    toktype.LSHIFT,
    toktype.RSHIFT,
    toktype.LTHAN,
    toktype.GTHAN,
    toktype.LTHANEQ,
    toktype.GTHANEQ,
    toktype.EQUAL,
    toktype.NEQUAL,
    toktype.BXOR,
    toktype.BOR,
    toktype.AND,
    toktype.OR,
    toktype.QMARK,
    toktype.COLON,
    toktype.SCOLON,
];